// flow-typed signature: 456baf6e2851e33cd6b4f8465cc00ab5
// flow-typed version: <<STUB>>/cpy-cli_v^1.0.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cpy-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cpy-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cpy-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cpy-cli/cli.js' {
  declare module.exports: $Exports<'cpy-cli/cli'>;
}
