// flow-typed signature: 5caec7178dfcfdd97b42fa4a1c922a37
// flow-typed version: <<STUB>>/random-emoji_v^1.0.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-emoji/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-emoji/index' {
  declare module.exports: $Exports<'random-emoji'>;
}
declare module 'random-emoji/index.js' {
  declare module.exports: $Exports<'random-emoji'>;
}
declare module 'random-emoji/test/test.js' {
  declare module.exports: $Exports<'random-emoji/test/test'>;
}
